### ISSUE TITLE
namespace(eureka) 配置文件发布失败

### ISSUE THREAD

**Issue by js179** [polarismesh/femas#167]
femas version: 1.0.0
命名空间(eureka版)下的配置文件发布时报错
![image](https://user-images.githubusercontent.com/96464038/174480981-ca095f69-5f0a-42a1-88d3-b7759aaa14b1.png)

**Comment by js179** [comment]
![image](https://user-images.githubusercontent.com/96464038/174481007-96d29087-fe02-46f6-8627-95e5e55159fc.png)

**Comment by js179** [comment]
我看源码中，没有eureka版配置中心的实现，目前只有nacos版本的

**Comment by zilongTong** [comment]
provide some error logs,please

**Comment by js179** [comment]
![image](https://user-images.githubusercontent.com/96464038/175185552-33d3fa92-a24f-4a10-9dde-75699cf50d8c.png)
