### ISSUE TITLE
项目无法拉取依赖包

### ISSUE THREAD

**Issue by willzhangsgit** [polarismesh/femas#185]
[ERROR] Failed to execute goal on project femas-springcloud-discovery-starter: Could not resolve dependencies for project com.tencent.tsf:femas-springcloud-discovery-starter:jar:1.0.0-SNAPSHOT: Could not find a
rtifact com.tencent.cloud:spring-cloud-tencent-metadata:jar:1.0.0.2020-SNAPSHOT in aliyunmaven (https://maven.aliyun.com/repository/public) -> [Help 1]
[ERROR]

是否是因为maven设置的为阿里云镜像，解决方案是什么呢?

**Comment by huyuanxin** [comment]
Please waiting for pull request merged and try again
