### ISSUE TITLE
eclipse导入工程编译报错

### ISSUE THREAD

**Issue by yanzl84** [polarismesh/femas#187]
pom.xml中提示：
Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:flatten-maven-plugin:
 1.1.0:flatten (execution: flatten, phase: process-resources)

**Comment by zilongTong** [comment]
We'll reproduce it later and try to fix it.

Try the following command:
mvn clean install -Dmaven.test.skip=true

**Comment by yanzl84** [comment]
已解决
