### ISSUE TITLE
不通过服务间调用的方式，服务鉴权不生效

### ISSUE THREAD

**Issue by yanzl84** [polarismesh/femas#194]
**操作步骤：**
启动Provider服务和gateway，在服务治理->服务鉴权中配置限制调用方IP的黑名单鉴权规则并生效，通过浏览器访问该Provider或gateway，鉴权规则无法生效。

应用场景：基于安全考虑，期望服务不管直接访问（浏览器、postman、其它工具）或者通过服务间调用都可以通过鉴权规则加以限制

**Comment by zilongTong** [comment]
fixed
