### ISSUE TITLE
Discussion: Breaking feedback mechanisms

### ISSUE THREAD

**Issue by MentosL** [polarismesh/femas#59]
环境情况：
代码分支：基于develop最新dubbo2.X系列
运行环境：macos M1

情况描述：
dubbo提供方设置超时时间大于消费方等待时间，反复调用之后，一直持续报出  ``` Invoke remote method timeout......```。只有等待提供方恢复正常状态下，消费方才能继续正常进行消费。

个人想法：
消费方调用之后，在一定时间内，根据返回异常 （such as ``` org.apache.dubbo.rpc.RpcException#TIMEOUT_EXCEPTION```）是否   是否可以在一定时间在```afte***Invoke ```将此接口进行降级或者限流措施，之后再根据外部触发控制 或者 内部一定时间内进行阈值放开进行调用？

@zilongTong 大佬有啥意见

**Comment by zilongTong** [comment]
femas有降级限流，配置了规则就可以生效

**Comment by MentosL** [comment]
我想表达的是： 如果前置没有配置，后面在访问过程中出现调用异常，是否需要增加降级限流（有点像自适应）

**Comment by zilongTong** [comment]
femas也支持内置的熔断降级，需要在femas.conf里面配置，没有任何配置的情况下就内置熔断降级，业务无法感知不透明

**Comment by MentosL** [comment]
GET   我明天再试试 途中降级措施（今天试了几次timeout的情况，发现没被限制住）
