### ISSUE TITLE
Agent-plugin: consul registry plugin

### ISSUE THREAD

**Issue by zilongTong** [polarismesh/femas#91]
## what do we want
help consul regitry support agent access
## how to achieve
follow the guidance : http://femas.io/doc/develop/agent_plugin.html
exampel:https://github.com/polarismesh/femas/blob/develop/femas-agent/femas-agent-plugin/femas-springcloud-plugin/femas-springcloud-greenwich-nacos-plugin/src/main/java/com/tencent/tsf/femas/agent/nacos/instrument/NacosServiceRegistryInterceptor.java

**Comment by MentosL** [comment]
Please assign it to me
